config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'coach', to: 'questions#coach'
  # Defines the root path route ("/")
  # root "articles#index"
  get 'answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def coach
  end

  def answer
    @question = params[:question]
    if @question == "I am going to work"
      @answer = "Great"
    elsif @question.include?('?')
      @answer = "Silly question, get dressed and go to work!"
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.typekit.net/mjp6hcp.css">
    <link rel="stylesheet" href="https://use.typekit.net/mjp6hcp.css">




    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h2><%= @question %><br>— You</h2>
<h2><%= @answer %><br>— Coach Vahid</h2>

<h2><%= link_to "Ask me something else, but choose wisely", coach_path %></h2>

app/views/questions/coach.html.erb
<div class="container">
  <h1>I'm coach Vahid, ask me something!</h1>
  <%=image_tag 'vahid.jpeg', :class => "img_preview"%>
  <form action="/answer">
    <div>
      <input type="text" name="question" placeholder="Ask me something" class="input-field">
    </div>
    <div>
    <input type="submit" value="Ask!" class="btn-ask">
    </div>
  </form>
</div>